#!/bin/zsh
if [[ $(hostname) == "renard" ]]
then
    trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 2560 --widthtype pixel --transparent true --alpha 0 --tint 0x002b36 --height 16
fi
