#
# Executes commands at logout.
#
# Authors:
#   Tim Millican <tim.millican@linux.com>
#

# Read local configuration {{{
if [[ -f ${ZDOTDIR:-$HOME}/.zlogout.local ]]; then
    source ${ZDOTDIR:-$HOME}/.zlogout.local
fi
# }}}

clear  # the screen

if [[ $USER != 'root' ]]; then
    echo 'The world is coming to an end--save your buffers!'
fi

# vim: fdm=marker syntax=zsh
