#
# Defines environment variables.
#
# Authors:
#   Tim Millican <tim.millican@linux.com>
#

# Read local configuration {{{
if [[ -f ${ZDOTDIR:-$HOME}/.zprofile.local ]]; then
    source ${ZDOTDIR:-$HOME}/.zprofile.local
fi
# }}}

# vim: fdm=marker syntax=zsh
