" {{{ General
" Sets how many lines of history VIM has to remember
set history=700

" Enable filetype plugins
filetype plugin on
filetype indent on

" Enable syntax highlighting
syntax enable

" Turn on Mode Lines
set modeline
set modelines=3

" Turn on (Relative)Line numbers
set number
set relativenumber

" Set terminal title
" autocmd BufEnter * let &titlestring = expand("%:t")
set title
" General }}}
" {{{ Files, backups and undo
" Keep backups in cache folder, so as not to clutter filesystem.
set backup
set backupdir=~/.cache/vim/backup,~/tmp,.,~/
set directory=~/.cache/vim/other,~/tmp,.,/var/tmp,/tmp
set undodir=~/.cache/vim/undo
set undofile
" Don't need backups for tmp files (usually sudo -e)
autocmd BufRead,BufEnter /var/tmp/* set nobackup noundofile nowritebackup
" Files, backups and undo }}}
" {{{ Plugins
call plug#begin('~/.config/NeoVim/plugged') " {{{
Plug 'altercation/vim-colors-solarized'
Plug 'benekastah/neomake'
Plug 'godlygeek/tabular', { 'on' : 'Tabularize' }
Plug 'Lokaltog/vim-easymotion'
Plug 'neovimhaskell/haskell-vim', { 'for' : 'haskell' }
Plug 'majutsushi/tagbar'
Plug 'pbrisbin/vim-syntax-shakespeare', { 'for' : ['hamlet','julius','casius','lucius'] }
Plug 'python.vim', { 'for' : 'python' }
Plug 'python_fold', { 'for' : 'python' }
Plug 'rodjek/vim-puppet', { 'for': 'puppet' }
Plug 'tommcdo/vim-exchange'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown', { 'for' : 'markdown' }
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'Twinside/vim-haskellConceal', { 'for' : 'haskell' }
Plug 'vim-utils/vim-man'
call plug#end() " }}}
" Plugin Configuration {{{
" Plugin 'altercation/vim-colors-solarized' {{{
set background=dark
colorscheme solarized
" }}}
" Plugin 'Lokaltog/vim-easymotion' {{{
let g:EasyMotion_do_mapping = 0 " Disable default mappings
let g:EasyMotion_keys = 'gpbkcwjrvqlzdihutenosa'

" Bi-directional find motion
" Jump to anywhere you want with minimal keystrokes, with just one key binding.
" `s{char}{label}`
" nmap s <Plug>(easymotion-s)
" or
" `s{char}{char}{label}`
" Need one more keystroke, but on average, it may be more comfortable.
nmap s <Plug>(easymotion-s2)

" Turn on case sensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
map ,j <Plug>(easymotion-j)
map ,k <Plug>(easymotion-k)

" Easy Motion }}}
" Plugin Configuration }}}
" Plugins }}}
" vim: fdm=marker
